# Generated by Django 2.0.5 on 2022-11-21 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('app_core', '0002_auto_20221121_1958'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidAlertOutQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_content', models.TextField()),
                ('device_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=400)),
                ('notification_type', models.CharField(max_length=255)),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=255)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('message_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_core.MessagingQueue')),
            ],
            options={
                'verbose_name': 'Android Alert Out Queue',
                'verbose_name_plural': 'Android Alert Out Queue',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='EmailOutQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('email_content', models.TextField()),
                ('recipient_email', models.EmailField(max_length=254)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('message_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_core.MessagingQueue')),
            ],
            options={
                'verbose_name': 'Email Out Queue',
                'verbose_name_plural': 'Email Out Queue',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
                ('event_details', models.TextField()),
                ('notified', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Class')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('priority', models.CharField(blank=True, choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('low', 'Low')], default='normal', max_length=120, null=True)),
                ('sms_message', models.TextField()),
                ('mobile_alert_message', models.TextField()),
                ('email_message', models.TextField()),
                ('sent', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipient_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Class')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='SchoolFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='feed_photo')),
                ('banner_address', models.CharField(blank=True, max_length=255)),
                ('video_link', models.CharField(blank=True, max_length=255)),
                ('video_id', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Soma360 Feed',
                'verbose_name_plural': 'Soma360 Feed',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='SchoolVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_link', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School')),
            ],
            options={
                'verbose_name': 'School Video',
                'verbose_name_plural': 'School Videos',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='SMSOutQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_content', models.TextField()),
                ('recipient_mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('message_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_core.MessagingQueue')),
            ],
            options={
                'verbose_name': 'SMS Out Queue',
                'verbose_name_plural': 'SMS Out Queue',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='smsoutqueue',
            unique_together={('message_ref', 'recipient_mobile')},
        ),
        migrations.AlterUniqueTogether(
            name='emailoutqueue',
            unique_together={('message_ref', 'recipient_email')},
        ),
        migrations.AlterUniqueTogether(
            name='androidalertoutqueue',
            unique_together={('message_ref', 'device_id')},
        ),
    ]
