# Generated by Django 2.0.5 on 2022-11-13 19:46

import app_core.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.SlugField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only.', unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.', 'invalid')], verbose_name='username')),
                ('firstname', models.CharField(blank=True, max_length=255, verbose_name='firstname')),
                ('lastname', models.CharField(blank=True, max_length=100, verbose_name='lastname')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, verbose_name='gender')),
                ('address', models.TextField(blank=True, max_length=255, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('contact_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='phone number')),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile')),
                ('is_staff', models.BooleanField(default=True, help_text='Only staff can directly login to the admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user can login to the system. Deactivate users instead of deleting accounts.', verbose_name='active')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered')),
                ('android_device_id', models.CharField(blank=True, max_length=200)),
                ('sms_notification', models.BooleanField(default=False)),
                ('mobile_notification', models.BooleanField(default=False)),
                ('email_notification', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
            managers=[
                ('objects', app_core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MessagingQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('short_message', models.TextField(blank=True, null=True)),
                ('notification_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sms_content', models.TextField()),
                ('email_content', models.TextField()),
                ('mobile_alert_content', models.TextField()),
                ('is_processed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Messaging Queue',
                'verbose_name_plural': 'Messaging Queue',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
