# Generated by Django 2.0.5 on 2022-11-21 19:58

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField()),
                ('is_admin', models.BooleanField(default=False)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=50, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.', 'invalid')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='last_name')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, verbose_name='gender')),
                ('address', models.TextField(blank=True, max_length=255, verbose_name='Address')),
                ('contact_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='phone number')),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user can login to the system. Deactivate users instead of deleting accounts.', verbose_name='active')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date registered')),
                ('android_device_id', models.CharField(blank=True, max_length=200)),
                ('sms_notification', models.BooleanField(default=False)),
                ('mobile_notification', models.BooleanField(default=False)),
                ('email_notification', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessagingQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('short_message', models.TextField(blank=True, null=True)),
                ('notification_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sms_content', models.TextField()),
                ('email_content', models.TextField()),
                ('mobile_alert_content', models.TextField()),
                ('is_processed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Messaging Queue',
                'verbose_name_plural': 'Messaging Queue',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
