# Generated by Django 2.0.5 on 2022-11-22 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_auto_20221122_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
