# Generated by Django 2.0.5 on 2022-11-21 19:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_year', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=255)),
                ('currently_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'School Year',
                'verbose_name_plural': 'School Years',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Class Name')),
                ('numeric_name', models.IntegerField(verbose_name='Numeric Name')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Class Description')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Class',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.AcademicYear')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Class')),
            ],
            options={
                'verbose_name': 'Class Subjects',
                'verbose_name_plural': 'Class Subjects',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='School Code')),
                ('name', models.CharField(max_length=255, verbose_name='School Name')),
                ('type', models.CharField(choices=[('primary', 'Primary School'), ('Secondary', 'Secondary School'), ('early_learning', 'Early Learning')], max_length=200, verbose_name='School Type')),
                ('address', models.TextField(blank=True, max_length=255, verbose_name='School Address')),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=255, verbose_name='E-mail Address')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('school_logo', sorl.thumbnail.fields.ImageField(blank=True, default=None, upload_to='images/school_logos/%Y/%m')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='SchoolTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('currently_active', models.BooleanField(default=False, help_text='Currently active school term.')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.AcademicYear')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School')),
            ],
            options={
                'verbose_name': 'School Term',
                'verbose_name_plural': 'School Terms',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Section Name')),
                ('description', models.TextField(max_length=255, verbose_name='Section Description')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.School')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.School')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subject',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AddField(
            model_name='classsubject',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school.Section'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.Subject'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teacher.Teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.School'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teacher.Teacher', verbose_name='Class Teacher'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.School'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('school_class', 'section', 'teacher', 'subject', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('numeric_year', 'school')},
        ),
    ]
