# Generated by Django 2.0.5 on 2022-11-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='middlename',
            new_name='middle_name',
        ),
    ]
